language: node_js
services: mongodb
cache:
  directories:
    - ~/.yarn
notifications:
  email: false
node_js:
  - "8"
  - "12"
before_script:
  - sleep 15
script:
  - yarn lint
  - yarn test
branches:
  only:
    - master
