name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        yarn install
    - name: Test
      run: |
        docker-compose up -d
        yarn test
        docker-compose down
      env:
        CI: true
        MONGO_URI: ${{ secrets.MONGO_URI }}
